### ISSUE TITLE
Implement Dad Jokes App

### ISSUE THREAD

**Issue by FarshadJanmohammadi** [Code-Coterie-Team/dad-jokes-app#1]
https://vannilla-js-basic-project-21-dad-jokes.netlify.app/

**Comment by faeze-amn** [comment]
fetch have a problem
@FarshadJanmohammadi

**Comment by FarshadJanmohammadi** [comment]
<button onClick={
        showJoke()
      }

توی این قسمت نباید کال کنید فقط باید اسم تابع رو بدی توی jsx شبیه html نیست که وقتی یه تایع رو به onclick میدیم بیایم کالش کنیم

**Comment by FarshadJanmohammadi** [comment]
در ضمن اون state که اسمشو showtext گذاشتی رو پاک کن

**Comment by faeze-amn** [comment]
الان دوباره Push کردم ولی خطا دارم
درست ازش استفاده میکنم داخل jsx

**Comment by FarshadJanmohammadi** [comment]
الان درسته نباید خطا داشته باشی، از خطایی که توی کنسول داری اسکرین بفرس

**Comment by faeze-amn** [comment]
![Uploading Screenshot (52).png…]()

**Comment by faeze-amn** [comment]
![Uploading Screenshot (52).png…]()

**Comment by faeze-amn** [comment]
@FarshadJanmohammadi

**Comment by faeze-amn** [comment]
![Uploading Screenshot (53).png…]()

**Comment by FarshadJanmohammadi** [comment]
توی تلگرام‌ میفرستی باز نمیشه
